AWSTemplateFormatVersion: 2010-09-09
Description: Share Directory.
Parameters:
  CodeBucket: 
    Description: Code Bucket
    Type: String
  ec2CreateRouteObjectVersion:
    Description: Object Version for ec2CreateRoute
    Type: String
  boto3cloudformationObjectVersion:
    Description: boto3cloudformationObjectVersion
    Type: String
  RouteTableId:
    Description: RouteTableId.
    Type: String
  DestinationCidrBlock:
    Description: DestinationCidrBlock.
    Type: String
  TransitGatewayId:
    Description: The AWS Account IDs to Share the Directory with.
    Type: String
Resources:
  myLambdaLayerboto3cloudformation:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: boto3cloudformation.zip
        S3ObjectVersion: !Ref boto3cloudformationObjectVersion
      Description: boto3cloudformation
      LayerName: boto3cloudformation
  ec2CreateRouteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ManageEvents
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutRule
            - events:DeleteRule
            - events:PutTargets
            - events:RemoveTargets
            - lambda:AddPermission
            - lambda:RemovePermission
            Resource: "*"
      - PolicyName: ManageRoutes
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:createRoute
            - ec2:replaceRoute
            - ec2:deleteRoute
            Resource: "*"
      - PolicyName: WriteToCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  ec2CreateRoute:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: ec2CreateRoute.zip
        S3ObjectVersion: !Ref ec2CreateRouteObjectVersion
      Handler: index.lambda_handler
      MemorySize: 2048
      Role: !GetAtt ec2CreateRouteRole.Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
      - !Ref myLambdaLayerboto3cloudformation
  ec2CreateRoutePrivateExecution:
    Type: Custom::ec2CreateRoute
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt ec2CreateRoute.Arn
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: !Ref DestinationCidrBlock
      TransitGatewayId: !Ref TransitGatewayId