AWSTemplateFormatVersion: 2010-09-09
Description: dsAcceptSharedDirectory.
Outputs: 
  DirectoryId: 
    Value: !GetAtt dsConnectDirectoryExecution.DirectoryId
Parameters:
  CodeBucket: 
    Description: S3 bucket hosting the Code.
    Type: String
  boto3cloudformationObjectVersion:
    Description: Lambda Layer containing updated boto3 with Cloudformation Helpers.
    Type: String
  FQDN: 
      Description: S3 bucket hosting the Code.
      Type: String
  ShortName: 
    Description: S3 bucket hosting the Code.
    Type: String
  VpcId: 
      Description: S3 bucket hosting the Code.
      Type: String
  Subnet1: 
    Description: S3 bucket hosting the Code.
    Type: String
  Subnet2: 
      Description: S3 bucket hosting the Code.
      Type: String
  DNS1: 
    Description: S3 bucket hosting the Code.
    Type: String
  DNS2: 
    Description: S3 bucket hosting the Code.
    Type: String
  CustomerUserName: 
    Description: S3 bucket hosting the Code.
    Type: String
  dsConnectDirectoryObjectVersion:
    Description: Fully Qualified domain name
    Type: String
  DirectoryPassword:
    Description: Fully Qualified domain name
    NoEcho: True
    Type: String
  Size:
    Description: Fully Qualified domain name
    Type: String
  
Resources:
  dsConnectDirectoryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ManageEvents
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutRule
            - events:DeleteRule
            - events:PutTargets
            - events:RemoveTargets
            - lambda:AddPermission
            - lambda:RemovePermission
            Resource: "*"
      - PolicyName: Directory
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ds:dsConnectDirectory
            - ds:*
            - ec2:*
            - ds:DeleteDirectory
            Resource: "*"
      - PolicyName: WriteToCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  myLambdaLayerboto3cloudformation:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: boto3cloudformation.zip
        S3ObjectVersion: !Ref boto3cloudformationObjectVersion
      Description: boto3cloudformation
      LayerName: boto3cloudformation
  dsConnectDirectory:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: dsConnectDirectory.zip
        S3ObjectVersion: !Ref dsConnectDirectoryObjectVersion
      Handler: index.lambda_handler
      MemorySize: 2048
      Role:
        Fn::GetAtt:
        - dsConnectDirectoryRole
        - Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
      - !Ref myLambdaLayerboto3cloudformation
  dsConnectDirectoryExecution:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt dsConnectDirectory.Arn
      Name: !Ref FQDN
      ShortName: !Ref ShortName
      Password: !Ref DirectoryPassword
      Description: "AD Connector"
      Size: !Ref Size
      VpcId: !Ref VpcId
      Subnet1: !Ref Subnet1
      Subnet2: !Ref Subnet2
      DNS1: !Ref DNS1
      DNS2: !Ref DNS2
      CustomerUserName: !Ref CustomerUserName