AWSTemplateFormatVersion: 2010-09-09
Description: Share Directory.
Parameters:
  CodeBucket: 
    Description: Code Bucket
    Type: String
  dsShareDirectoryObjectVersion:
    Description: Fully Qualified domain name
    Type: String
  boto3cloudformationObjectVersion:
    Description: boto3cloudformationObjectVersion
    Type: String
  ShareNotes:
    Description: A Note to send to the AWS Account your sharing the Directory with.
    Type: String
  myDirectory:
    Description: DirectoryId to share.
    Type: String
  ShareTargetIds:
    Description: The AWS Account IDs to Share the Directory with.
    Type: CommaDelimitedList
Resources:
  myLambdaLayerboto3cloudformation:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: boto3cloudformation.zip
        S3ObjectVersion: !Ref boto3cloudformationObjectVersion
      Description: boto3cloudformation
      LayerName: boto3cloudformation
  dsShareDirectoryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ManageEvents
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutRule
            - events:DeleteRule
            - events:PutTargets
            - events:RemoveTargets
            - lambda:AddPermission
            - lambda:RemovePermission
            Resource: "*"
      - PolicyName: Directory
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ds:*
            - ec2:*
            Resource: "*"
      - PolicyName: WriteToCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
  dsShareDirectory:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: dsShareDirectory.zip
        S3ObjectVersion: !Ref dsShareDirectoryObjectVersion
      Handler: index.lambda_handler
      MemorySize: 2048
      Role:
        Fn::GetAtt:
        - dsShareDirectoryRole
        - Arn
      Runtime: python3.6
      Timeout: 120
      Layers:
      - !Ref myLambdaLayerboto3cloudformation
  dsShareDirectoryExecution:
    Type: Custom::ShareDirectory
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt dsShareDirectory.Arn
      DirectoryId: !Ref myDirectory
      ShareNotes: !Ref ShareNotes
      ShareTargetIds: !Ref ShareTargetIds