AWSTemplateFormatVersion: 2010-09-09
Description: ramCreateResourceShare Example.
Parameters:
  Principals:
    Description: A List of ARNs to share resources with.
    Type: CommaDelimitedList
  ResourceArns:
    Description: A List of ARNs to share resources with.
    Type: CommaDelimitedList
  CodeBucket:
    Description: CodeBucket.
    Type: String
  ramCreateResourceShareObjectVersion:
    Description: ramCreateResourceShareObjectVersion.
    Type: String
  boto3cloudformationObjectVersion:
    Description: boto3cloudformationObjectVersion
    Type: String
Resources:
  ramCreateResourceShareExecution:
    Type: Custom::ramCreateResourceShare
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt ramCreateResourceShare.Arn
      Name: AltitudeShare
      Principals: !Ref Principals
      ResourceArns: !Ref ResourceArns
  myLambdaLayerboto3cloudformation:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.6
      Content: 
        S3Bucket: !Ref CodeBucket
        S3Key: boto3cloudformation.zip
        S3ObjectVersion: !Ref boto3cloudformationObjectVersion
      Description: boto3cloudformation
      LayerName: boto3cloudformation
  ramCreateResourceShare:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: ramCreateResourceShare.zip
        S3ObjectVersion: !Ref ramCreateResourceShareObjectVersion
      Handler: index.lambda_handler
      MemorySize: 2048
      Role: !GetAtt ramCreateResourceShareRole.Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
      - !Ref myLambdaLayerboto3cloudformation
  ramCreateResourceShareRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: ManageShares
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ram:*
            - ec2:DescribeTransitGateways
            Resource: "*"
      - PolicyName: ManageEvents
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - events:PutRule
            - events:DeleteRule
            - events:PutTargets
            - events:RemoveTargets
            - lambda:AddPermission
            - lambda:RemovePermission
            Resource: "*"
      - PolicyName: WriteToCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"